import { ActivityCard } from '../types/ActivityCard';

export const mockActivities: ActivityCard[] = [
  {
    id: 1,
    imageSrc: '/assets/activity-images/Maleri-workshop.jpg',
    name: 'Anders Jensen',
    email: 'anders.jensen@example.com',
    phone: '22 47 80 28',
    title: 'Maleri Workshop',
    subTitle: 'Lær at male smukke landskaber.',
    description:
      'I dag skal vi lære at male smukke landskaber og portrætter. Husk din pænsel og lærred',
    ageGroup: '7-10 år',
    time: '10:00',
    date: new Date('2023-11-01'),
    participants: 15,
    location: 'København',
    category: 'Kreativt',
    region: 'Hovedstaden',
  },
  {
    id: 2,
    imageSrc: '/assets/activity-images/Fodboldtræning.jpg',
    name: 'Mette Larsen',
    email: 'mette.larsen@example.com',
    phone: '29 57 80 23',
    title: 'Fodboldtræning',
    subTitle: 'Træn teknik og samspil i fodbold.',
    description:
      'Vi skal have gang i noget teknik og samspil, vi kommer til at lave forskellige øvelser. Til sidst spiller vi en træningskamp',
    ageGroup: '11-13 år',
    time: '15:00',
    date: new Date('2023-11-10'),
    participants: 20,
    location: 'Roskilde',
    category: 'Sport',
    region: 'Midtsjælland',
  },
  {
    id: 3,
    imageSrc: '/assets/activity-images/Skovtur.jpg',
    name: 'Frederik Madsen',
    email: 'frederik.madsen@example.com',
    phone: '23 45 67 89',
    title: 'Familietur i skoven',
    subTitle: 'Nyde naturen og lave bål sammen',
    description:
      'Perfekt mulighed for at mærke naturen, hvor vi afslutter med et bål og skumfiduser',
    ageGroup: '0-3 år',
    time: '12:30',
    date: new Date('2023-11-05'),
    participants: 10,
    location: 'Skovlunde',
    category: 'Udendørs',
    region: 'Hovedstaden',
  },
  {
    id: 4,
    imageSrc: '/assets/activity-images/Gaming.jpg',
    name: 'Louise Kristensen',
    email: 'louise.kristensen@example.com',
    phone: '27 40 26 21',
    title: 'Gaming aften',
    subTitle: 'Spil forskellige multiplayer spil.',
    description:
      'Vi prøver kræfter med forskellige spil, som Counter-Strike, Fortnite, og andre ønsker.',
    ageGroup: '11-13 år',
    time: '19:00',
    date: new Date('2023-11-20'),
    participants: 8,
    location: 'Horsens',
    category: 'Gaming',
    region: 'Østjylland',
  },
  {
    id: 5,
    imageSrc: '/assets/activity-images/Ler-workshop.jpg',
    name: 'Peter Nielsen',
    email: 'peter.nielsen@example.com',
    phone: '21 80 27 37',
    title: 'Ler workshop',
    subTitle: 'Lav dine egne skåle og vaser.',
    description:
      'Vi starter ud med at lære hvordan man drejer sin ler, som forhåbentlig ender ud i en skål eller vase.',
    ageGroup: '4-6 år',
    time: '13:00',
    date: new Date('2023-11-26'),
    participants: 12,
    location: 'Holstebro',
    category: 'Kreativt',
    region: 'Vestjylland',
  },
  {
    id: 6,
    imageSrc: '/assets/activity-images/Trick-or-treat.jpg',
    name: 'Anders Hansen',
    email: 'andershansen@example.com',
    phone: '34567532',
    title: 'Trick or treat',
    subTitle: 'Halloween railing',
    description:
      'Jeg vil gerne arrangere at gå rundt i samlet flok i byen med børnene, og rasle. Min kone og jeg holder opsyn med de små poder, mens vi går rundt. Så meld gerne jeres børn til, så vi kan have en hyggelig aften! Aldersgruppen er selvfølgelig vejledende, der er plads til alle.',
    ageGroup: '7-10 år',
    time: '19:00',
    date: new Date('2023-10-31'),
    participants: 15,
    location: 'Vemmelev',
    category: 'Udendørs',
    region: 'Vestsjælland',
  },
  {
    id: 7,
    imageSrc: '/assets/activity-images/Bage-workshop.jpg',
    name: 'Jane Grønbech',
    email: 'jane1983@example.com',
    phone: '98574548',
    title: 'Bage Workshop',
    subTitle: 'Den lille bagedyst',
    description:
      'Der er måske andre som os, der ser meget Den Store Bagedyst derhjemme. Så jeg vil gerne ligge køkken til en bage dag! Vi kommer til at bage nogle kager og hjælpes ad med at dekorerer dem, og selvfølgelig smage på dem også! ;-)',
    ageGroup: '7-10 år',
    time: '11:00',
    date: new Date('2023-11-04'),
    participants: 7,
    location: 'Birkerød',
    category: 'Kreativt',
    region: 'Hovedstaden',
  },
  {
    id: 8,
    imageSrc: '/assets/activity-images/Mødregruppe.jpg',
    name: 'Signe Bech',
    email: 'frubech@example.com',
    phone: '73682681',
    title: 'Mødregruppe',
    subTitle: 'For mødre med kolikbørn',
    description:
      'Måske der er andre som mig der har et barn med kolik. Syntes det kunne være rigtig hyggeligt at starte vores egen mødregruppe, med ligesindede der kan forstå den problematik vi til tider oplever. Det foregår hjemme hos mig, og der vil selvfølgelig være forfriskninger!',
    ageGroup: '0-3 år',
    time: '10:30',
    date: new Date('2023-11-01'),
    participants: 5,
    location: 'Vejle',
    category: 'Legeaftale',
    region: 'Østjylland',
  },
  {
    id: 9,
    imageSrc: '/assets/activity-images/Julepynt.jpg',
    name: 'Maj Søndergaard',
    email: 'mysse71@example.com',
    phone: '76580865',
    title: 'Klippeklistre',
    subTitle: 'Julepynts workshop',
    description:
      'Lad os have en hyggelig dag, hvor vi laver vores eget julepynt! Jeg har sørget for pap, sakse, lim stifter og glimmer. Både for børn og voksne - en hyggelig dag hvor vi gør os klar til julen sammen.',
    ageGroup: '4-6 år',
    time: '14:00',
    date: new Date('2023-12-03'),
    participants: 8,
    location: 'Stenlille',
    category: 'Kreativt',
    region: 'Vestsjælland',
  },
  {
    id: 10,
    imageSrc: '/assets/activity-images/Mario-kart.jpg',
    name: 'Troels Engell',
    email: 't.engell@example.com',
    phone: '83622927',
    title: 'MarioKart',
    subTitle: 'MarioKart turnering',
    description:
      ' En rigtig hygge aften hvor der bare skal spilles derud af! Vi starter kl. 19.00 og der bliver derfor også budt på pizza og sodavand. Vi har 2 Nintendo Switch, og derfor kan der være kun være 8 deltagere. Både drenge og piger er velkomne!',
    ageGroup: '11-13 år',
    time: '19:00',
    date: new Date('2023-11-18'),
    participants: 8,
    location: 'Søborg',
    category: 'Gaming',
    region: 'Hovedstaden',
  },
];
